services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=sport
    ports:
      - '5434:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: sport@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8989:80"
